apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: feature-flags
type: Opaque
data:
  # PostgreSQL RDS connection strings
  DATABASE_URL_AUTH: "cG9zdGdyZXM6Ly9wb3N0Z3Jlczo3VlU2cTNiVjhUb1hAYXV0aC1kYi5jOXZ2cjVsejlid2QudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvYXV0aF9kYg=="
  DATABASE_URL_FLAG: "cG9zdGdyZXM6Ly9wb3N0Z3JlczpKQjk0RTloWHc5SHdAZmxhZ3MtZGIuYzl2dnI1bHo5YndkLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL2ZsYWdfZGI="
  DATABASE_URL_TARGETING: "cG9zdGdyZXM6Ly9wb3N0Z3JlczpGODc0RndYZWY5cEpAdGFyZ2V0aW5nLWRiLmM5dnZyNWx6OWJ3ZC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi90YXJnZXRpbmdfZGI="

  # ElastiCache Redis endpoint
  REDIS_URL: "cmVkaXNzOi8vbWFzdGVyLnRvZ2dsZW1hc3Rlci1yZWRpcy51cjB1a3AudXNlMS5jYWNoZS5hbWF6b25hd3MuY29tOjYzNzk="

  # SQS queue URL
  AWS_SQS_URL: "aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vMjQ4NTMwNTUxNTEwL3Rvb2dsZW1hc3Rlci1ldmFsdWF0aW9uLWV2ZW50cy1xdWV1ZQ=="

  # Auth service master key
  MASTER_KEY: "YWRtaW4tc2VjcmV0by0xMjM="

  # Pre-generated service API key (must match a key created in auth-service)
  SERVICE_API_KEY: "dG1fa2V5X2Rldg=="
